### PR TITLE
Issue #9 - Add base functionality for summary of a code. It restructu…

### PR DESCRIPTION
**Pull request by TenshiLyle**
…re and simplified the data return by the Php Parser.

### CODE REVIEW

**Comment by TenshiLyle** [comment]
@tbasilio @sandaemc @nlabrador 

After several revision, I've decided to do it this way. The goal is to help authors analyze the code. Basically, I restructure the data given by the Php Parser and remove the objects. You can say it will generate a report summary of a given code. As an example, if we have this code

```
$name = "Jerome"

echo $jerome;
```

This will give us
```
Array(
 ['variables'] => Array(
  'name'
 )
 ['construct'] => Array(
  ['echo'] => Array(
    [0] => Array(
      ['type'] => 'variable',
      ['value'] => 'Variable:name'
   )
  )
 )
)
```

Really want to know what your thoughts are on this approach.

**Comment by sandaemc** [comment]
Do you have an example usage where it become easier for content writers to write proof?

**Comment by TenshiLyle** [comment]
Example Question:
```php
$var = 1;
```
 Given the following code, use the increment operator so that variable `$var` will have a value of 10.

Old way from the IntegerDataType/tests/Extras/IncrementTest.php file. This is still a weak test since it didn't test if the increment operator was used on the same variable
```php

use Proofs\Proof;
class IncrementTest extends Proof
{
    public function testSyntax()
    {
        $validUserCode = $this->syntaxCheckUserCode();
        $this->assertEquals(0, $validUserCode, "Syntax Error Check");
    }
    /**
     * @depends testSyntax
     */
    public function testIncrement()
    {
        $nodes = $this->parsePhpAnswer();
        $incrementNode = $this->findIncrementNode( $nodes );
        if ( $incrementNode instanceof PhpParser\Node\Expr\PreInc )
        {
            $this->assertInstanceOf('PhpParser\Node\Expr\PreInc', $incrementNode, 'Pre Increment operator used');
        }
        elseif ( $incrementNode instanceof PhpParser\Node\Expr\PostInc )
        {
            $this->assertInstanceOf('PhpParser\Node\Expr\PostInc', $incrementNode, 'Post Increment operator used');
        }
        else
        {
            $this->assertNotNull($incrementNode, "No increment operator used.");
        }
        return $nodes;
    }
    /**
     * @depends testIncrement
     */
    public function testIncrementToTen( array $nodes )
    {
        $incrementNodes = array_values(
            array_filter( $nodes, function($value) {
                if ( $value instanceof PhpParser\Node\Expr\PreInc || $value instanceof PhpParser\Node\Expr\PostInc )
                {
                    return true;
                }
                else
                {
                    return false;
                }
            })
        );
        $this->assertEquals(10, count($incrementNodes), "Increment operator used 10 times to give us a value of 10");
    }
}
```

With this library
```php
use CodingAvenue\Proof\Code;
use PHPUnit\Framework\TestCase;

class IncrementTest extends TestCase
{
  protected $code;
  protected function setup()
  {
    $this->code = new Code();
  }
  public function testSyntax()
  {
   $evaluator = $this->code->evaluator();
   $result = $evaluator->evaluate();
   $this->assertEqual('', $result['error'], 'syntax check');
  }

 public function testIncrement()
 {
  $summary = $this->code->parser()->getSummary();
  // We will need to have a secondary argument, which will serve as an additional filter. E.g. if I want to filter the increment to using Post Increment or if I want to filter the Increment operator to a certain variable.
  $increments = $summary->getOperator('increment'); 
  $this->assertEqual(10, count($increments), "Increment Operator was used 10 times);
 }
}
```

**Comment by TenshiLyle** [comment]
I would imagine, Proof writer will create a parent class which will extend PHPUnit TestCase. And have the setup() method in there. This way they don't need to always create that method on every proof file.

**Comment by TenshiLyle** [comment]
An Update on the usage, to get the increment operator the author will now do
```php
public functin testIncrement()
{
 $nodes = $code->parser()->getNodes();
 $finder = new NodeFinder();

 // Will find an increment operator used on variable 'var'
 $increments = $finder->findOperator($nodes, ['name' => 'increment', 'variable' => 'var']);
 $this->assertEqual(10, count($increments), "Increment Operator was used 10 times on variable 'var'");
}
```

**Comment by sandaemc** [comment]
Can we achieve this?

```php
$code->find('++$var')->count();

// or

$code->find('$var:increment')->count();
```

**Comment by TenshiLyle** [comment]
@sandaemc sorry,

My notification was delayed your comment on this PR. I've merged the PR already. I'll create an issue so we can discuss it there.

**Pull request merged**
